$.pnotify.defaults.styling = "bootstrap3"
$.pnotify.defaults.history = false
$.pnotify.defaults.stack = {"dir1": "up", "dir2": "left", "push": "left"}
$.pnotify.defaults.addclass = "stack-bottomright"
$.pnotify.defaults.nonblock = {nonblock: true, nonblock_opacity: 0.2}
$.pnotify.defaults.closer = false
$.pnotify.defaults.sticker = false
$.pnotify.defaults.hide = true
$.pnotify.defaults.delay = 2000
